/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as WebsiteWebsiteIdRouteImport } from './routes/website.$websiteId'
import { Route as DashboardWhatsappSalesRouteImport } from './routes/dashboard.whatsapp-sales'
import { Route as DashboardWhatsappRouteImport } from './routes/dashboard.whatsapp'
import { Route as DashboardWebsiteRouteImport } from './routes/dashboard.website'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSeoGoogleMapsRouteImport } from './routes/dashboard.seo-google-maps'
import { Route as DashboardSeoRouteImport } from './routes/dashboard.seo'
import { Route as DashboardReviewReplyRouteImport } from './routes/dashboard.review-reply'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardPricingRouteImport } from './routes/dashboard.pricing'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard.messages'
import { Route as DashboardInstagramRouteImport } from './routes/dashboard.instagram'
import { Route as DashboardInsightsRouteImport } from './routes/dashboard.insights'
import { Route as DashboardGrowthRouteImport } from './routes/dashboard.growth'
import { Route as DashboardDailyAskRouteImport } from './routes/dashboard.daily-ask'
import { Route as DashboardCustomersRouteImport } from './routes/dashboard.customers'
import { Route as DashboardContentRouteImport } from './routes/dashboard.content'
import { Route as DashboardCompetitorsRouteImport } from './routes/dashboard.competitors'
import { Route as DashboardCompetitorAnalysisRouteImport } from './routes/dashboard.competitor-analysis'
import { Route as DashboardBusinessDetailsRouteImport } from './routes/dashboard.business-details'
import { Route as DashboardBusinessAnalysisRouteImport } from './routes/dashboard.business-analysis'
import { Route as DashboardBlogsRouteImport } from './routes/dashboard.blogs'
import { Route as DashboardB2bNetworkRouteImport } from './routes/dashboard.b2b-network'
import { Route as DashboardAutomationRouteImport } from './routes/dashboard.automation'
import { Route as DashboardAeoGeoRouteImport } from './routes/dashboard.aeo-geo'
import { Route as DashboardActionsRouteImport } from './routes/dashboard.actions'
import { Route as DashboardAgentsIndexRouteImport } from './routes/dashboard.agents.index'
import { Route as DashboardBusinessAnalysisOldRouteImport } from './routes/dashboard.business-analysis.old'
import { Route as DashboardAgentsPartnershipRouteImport } from './routes/dashboard.agents.partnership'
import { Route as DashboardAgentsCustomerRetentionRouteImport } from './routes/dashboard.agents.customer-retention'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const WebsiteWebsiteIdRoute = WebsiteWebsiteIdRouteImport.update({
  id: '/website/$websiteId',
  path: '/website/$websiteId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWhatsappSalesRoute = DashboardWhatsappSalesRouteImport.update({
  id: '/whatsapp-sales',
  path: '/whatsapp-sales',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWhatsappRoute = DashboardWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWebsiteRoute = DashboardWebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSeoGoogleMapsRoute = DashboardSeoGoogleMapsRouteImport.update({
  id: '/seo-google-maps',
  path: '/seo-google-maps',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSeoRoute = DashboardSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReviewReplyRoute = DashboardReviewReplyRouteImport.update({
  id: '/review-reply',
  path: '/review-reply',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPricingRoute = DashboardPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInstagramRoute = DashboardInstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInsightsRoute = DashboardInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGrowthRoute = DashboardGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDailyAskRoute = DashboardDailyAskRouteImport.update({
  id: '/daily-ask',
  path: '/daily-ask',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomersRoute = DashboardCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContentRoute = DashboardContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCompetitorsRoute = DashboardCompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCompetitorAnalysisRoute =
  DashboardCompetitorAnalysisRouteImport.update({
    id: '/competitor-analysis',
    path: '/competitor-analysis',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardBusinessDetailsRoute =
  DashboardBusinessDetailsRouteImport.update({
    id: '/business-details',
    path: '/business-details',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardBusinessAnalysisRoute =
  DashboardBusinessAnalysisRouteImport.update({
    id: '/business-analysis',
    path: '/business-analysis',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardBlogsRoute = DashboardBlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardB2bNetworkRoute = DashboardB2bNetworkRouteImport.update({
  id: '/b2b-network',
  path: '/b2b-network',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAutomationRoute = DashboardAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAeoGeoRoute = DashboardAeoGeoRouteImport.update({
  id: '/aeo-geo',
  path: '/aeo-geo',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardActionsRoute = DashboardActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgentsIndexRoute = DashboardAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBusinessAnalysisOldRoute =
  DashboardBusinessAnalysisOldRouteImport.update({
    id: '/old',
    path: '/old',
    getParentRoute: () => DashboardBusinessAnalysisRoute,
  } as any)
const DashboardAgentsPartnershipRoute =
  DashboardAgentsPartnershipRouteImport.update({
    id: '/agents/partnership',
    path: '/agents/partnership',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAgentsCustomerRetentionRoute =
  DashboardAgentsCustomerRetentionRouteImport.update({
    id: '/agents/customer-retention',
    path: '/agents/customer-retention',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/dashboard/actions': typeof DashboardActionsRoute
  '/dashboard/aeo-geo': typeof DashboardAeoGeoRoute
  '/dashboard/automation': typeof DashboardAutomationRoute
  '/dashboard/b2b-network': typeof DashboardB2bNetworkRoute
  '/dashboard/blogs': typeof DashboardBlogsRoute
  '/dashboard/business-analysis': typeof DashboardBusinessAnalysisRouteWithChildren
  '/dashboard/business-details': typeof DashboardBusinessDetailsRoute
  '/dashboard/competitor-analysis': typeof DashboardCompetitorAnalysisRoute
  '/dashboard/competitors': typeof DashboardCompetitorsRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/daily-ask': typeof DashboardDailyAskRoute
  '/dashboard/growth': typeof DashboardGrowthRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/instagram': typeof DashboardInstagramRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/pricing': typeof DashboardPricingRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/review-reply': typeof DashboardReviewReplyRoute
  '/dashboard/seo': typeof DashboardSeoRoute
  '/dashboard/seo-google-maps': typeof DashboardSeoGoogleMapsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/website': typeof DashboardWebsiteRoute
  '/dashboard/whatsapp': typeof DashboardWhatsappRoute
  '/dashboard/whatsapp-sales': typeof DashboardWhatsappSalesRoute
  '/website/$websiteId': typeof WebsiteWebsiteIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/agents/customer-retention': typeof DashboardAgentsCustomerRetentionRoute
  '/dashboard/agents/partnership': typeof DashboardAgentsPartnershipRoute
  '/dashboard/business-analysis/old': typeof DashboardBusinessAnalysisOldRoute
  '/dashboard/agents/': typeof DashboardAgentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/dashboard/actions': typeof DashboardActionsRoute
  '/dashboard/aeo-geo': typeof DashboardAeoGeoRoute
  '/dashboard/automation': typeof DashboardAutomationRoute
  '/dashboard/b2b-network': typeof DashboardB2bNetworkRoute
  '/dashboard/blogs': typeof DashboardBlogsRoute
  '/dashboard/business-analysis': typeof DashboardBusinessAnalysisRouteWithChildren
  '/dashboard/business-details': typeof DashboardBusinessDetailsRoute
  '/dashboard/competitor-analysis': typeof DashboardCompetitorAnalysisRoute
  '/dashboard/competitors': typeof DashboardCompetitorsRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/daily-ask': typeof DashboardDailyAskRoute
  '/dashboard/growth': typeof DashboardGrowthRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/instagram': typeof DashboardInstagramRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/pricing': typeof DashboardPricingRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/review-reply': typeof DashboardReviewReplyRoute
  '/dashboard/seo': typeof DashboardSeoRoute
  '/dashboard/seo-google-maps': typeof DashboardSeoGoogleMapsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/website': typeof DashboardWebsiteRoute
  '/dashboard/whatsapp': typeof DashboardWhatsappRoute
  '/dashboard/whatsapp-sales': typeof DashboardWhatsappSalesRoute
  '/website/$websiteId': typeof WebsiteWebsiteIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/agents/customer-retention': typeof DashboardAgentsCustomerRetentionRoute
  '/dashboard/agents/partnership': typeof DashboardAgentsPartnershipRoute
  '/dashboard/business-analysis/old': typeof DashboardBusinessAnalysisOldRoute
  '/dashboard/agents': typeof DashboardAgentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/dashboard/actions': typeof DashboardActionsRoute
  '/dashboard/aeo-geo': typeof DashboardAeoGeoRoute
  '/dashboard/automation': typeof DashboardAutomationRoute
  '/dashboard/b2b-network': typeof DashboardB2bNetworkRoute
  '/dashboard/blogs': typeof DashboardBlogsRoute
  '/dashboard/business-analysis': typeof DashboardBusinessAnalysisRouteWithChildren
  '/dashboard/business-details': typeof DashboardBusinessDetailsRoute
  '/dashboard/competitor-analysis': typeof DashboardCompetitorAnalysisRoute
  '/dashboard/competitors': typeof DashboardCompetitorsRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/daily-ask': typeof DashboardDailyAskRoute
  '/dashboard/growth': typeof DashboardGrowthRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/instagram': typeof DashboardInstagramRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/pricing': typeof DashboardPricingRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/review-reply': typeof DashboardReviewReplyRoute
  '/dashboard/seo': typeof DashboardSeoRoute
  '/dashboard/seo-google-maps': typeof DashboardSeoGoogleMapsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/website': typeof DashboardWebsiteRoute
  '/dashboard/whatsapp': typeof DashboardWhatsappRoute
  '/dashboard/whatsapp-sales': typeof DashboardWhatsappSalesRoute
  '/website/$websiteId': typeof WebsiteWebsiteIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/agents/customer-retention': typeof DashboardAgentsCustomerRetentionRoute
  '/dashboard/agents/partnership': typeof DashboardAgentsPartnershipRoute
  '/dashboard/business-analysis/old': typeof DashboardBusinessAnalysisOldRoute
  '/dashboard/agents/': typeof DashboardAgentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/verify'
    | '/dashboard/actions'
    | '/dashboard/aeo-geo'
    | '/dashboard/automation'
    | '/dashboard/b2b-network'
    | '/dashboard/blogs'
    | '/dashboard/business-analysis'
    | '/dashboard/business-details'
    | '/dashboard/competitor-analysis'
    | '/dashboard/competitors'
    | '/dashboard/content'
    | '/dashboard/customers'
    | '/dashboard/daily-ask'
    | '/dashboard/growth'
    | '/dashboard/insights'
    | '/dashboard/instagram'
    | '/dashboard/messages'
    | '/dashboard/pricing'
    | '/dashboard/reports'
    | '/dashboard/review-reply'
    | '/dashboard/seo'
    | '/dashboard/seo-google-maps'
    | '/dashboard/settings'
    | '/dashboard/website'
    | '/dashboard/whatsapp'
    | '/dashboard/whatsapp-sales'
    | '/website/$websiteId'
    | '/dashboard/'
    | '/dashboard/agents/customer-retention'
    | '/dashboard/agents/partnership'
    | '/dashboard/business-analysis/old'
    | '/dashboard/agents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/verify'
    | '/dashboard/actions'
    | '/dashboard/aeo-geo'
    | '/dashboard/automation'
    | '/dashboard/b2b-network'
    | '/dashboard/blogs'
    | '/dashboard/business-analysis'
    | '/dashboard/business-details'
    | '/dashboard/competitor-analysis'
    | '/dashboard/competitors'
    | '/dashboard/content'
    | '/dashboard/customers'
    | '/dashboard/daily-ask'
    | '/dashboard/growth'
    | '/dashboard/insights'
    | '/dashboard/instagram'
    | '/dashboard/messages'
    | '/dashboard/pricing'
    | '/dashboard/reports'
    | '/dashboard/review-reply'
    | '/dashboard/seo'
    | '/dashboard/seo-google-maps'
    | '/dashboard/settings'
    | '/dashboard/website'
    | '/dashboard/whatsapp'
    | '/dashboard/whatsapp-sales'
    | '/website/$websiteId'
    | '/dashboard'
    | '/dashboard/agents/customer-retention'
    | '/dashboard/agents/partnership'
    | '/dashboard/business-analysis/old'
    | '/dashboard/agents'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/verify'
    | '/dashboard/actions'
    | '/dashboard/aeo-geo'
    | '/dashboard/automation'
    | '/dashboard/b2b-network'
    | '/dashboard/blogs'
    | '/dashboard/business-analysis'
    | '/dashboard/business-details'
    | '/dashboard/competitor-analysis'
    | '/dashboard/competitors'
    | '/dashboard/content'
    | '/dashboard/customers'
    | '/dashboard/daily-ask'
    | '/dashboard/growth'
    | '/dashboard/insights'
    | '/dashboard/instagram'
    | '/dashboard/messages'
    | '/dashboard/pricing'
    | '/dashboard/reports'
    | '/dashboard/review-reply'
    | '/dashboard/seo'
    | '/dashboard/seo-google-maps'
    | '/dashboard/settings'
    | '/dashboard/website'
    | '/dashboard/whatsapp'
    | '/dashboard/whatsapp-sales'
    | '/website/$websiteId'
    | '/dashboard/'
    | '/dashboard/agents/customer-retention'
    | '/dashboard/agents/partnership'
    | '/dashboard/business-analysis/old'
    | '/dashboard/agents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  VerifyRoute: typeof VerifyRoute
  WebsiteWebsiteIdRoute: typeof WebsiteWebsiteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/website/$websiteId': {
      id: '/website/$websiteId'
      path: '/website/$websiteId'
      fullPath: '/website/$websiteId'
      preLoaderRoute: typeof WebsiteWebsiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/whatsapp-sales': {
      id: '/dashboard/whatsapp-sales'
      path: '/whatsapp-sales'
      fullPath: '/dashboard/whatsapp-sales'
      preLoaderRoute: typeof DashboardWhatsappSalesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/whatsapp': {
      id: '/dashboard/whatsapp'
      path: '/whatsapp'
      fullPath: '/dashboard/whatsapp'
      preLoaderRoute: typeof DashboardWhatsappRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/website': {
      id: '/dashboard/website'
      path: '/website'
      fullPath: '/dashboard/website'
      preLoaderRoute: typeof DashboardWebsiteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/seo-google-maps': {
      id: '/dashboard/seo-google-maps'
      path: '/seo-google-maps'
      fullPath: '/dashboard/seo-google-maps'
      preLoaderRoute: typeof DashboardSeoGoogleMapsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/seo': {
      id: '/dashboard/seo'
      path: '/seo'
      fullPath: '/dashboard/seo'
      preLoaderRoute: typeof DashboardSeoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/review-reply': {
      id: '/dashboard/review-reply'
      path: '/review-reply'
      fullPath: '/dashboard/review-reply'
      preLoaderRoute: typeof DashboardReviewReplyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pricing': {
      id: '/dashboard/pricing'
      path: '/pricing'
      fullPath: '/dashboard/pricing'
      preLoaderRoute: typeof DashboardPricingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/instagram': {
      id: '/dashboard/instagram'
      path: '/instagram'
      fullPath: '/dashboard/instagram'
      preLoaderRoute: typeof DashboardInstagramRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/insights': {
      id: '/dashboard/insights'
      path: '/insights'
      fullPath: '/dashboard/insights'
      preLoaderRoute: typeof DashboardInsightsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/growth': {
      id: '/dashboard/growth'
      path: '/growth'
      fullPath: '/dashboard/growth'
      preLoaderRoute: typeof DashboardGrowthRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/daily-ask': {
      id: '/dashboard/daily-ask'
      path: '/daily-ask'
      fullPath: '/dashboard/daily-ask'
      preLoaderRoute: typeof DashboardDailyAskRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/customers': {
      id: '/dashboard/customers'
      path: '/customers'
      fullPath: '/dashboard/customers'
      preLoaderRoute: typeof DashboardCustomersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/content': {
      id: '/dashboard/content'
      path: '/content'
      fullPath: '/dashboard/content'
      preLoaderRoute: typeof DashboardContentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/competitors': {
      id: '/dashboard/competitors'
      path: '/competitors'
      fullPath: '/dashboard/competitors'
      preLoaderRoute: typeof DashboardCompetitorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/competitor-analysis': {
      id: '/dashboard/competitor-analysis'
      path: '/competitor-analysis'
      fullPath: '/dashboard/competitor-analysis'
      preLoaderRoute: typeof DashboardCompetitorAnalysisRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/business-details': {
      id: '/dashboard/business-details'
      path: '/business-details'
      fullPath: '/dashboard/business-details'
      preLoaderRoute: typeof DashboardBusinessDetailsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/business-analysis': {
      id: '/dashboard/business-analysis'
      path: '/business-analysis'
      fullPath: '/dashboard/business-analysis'
      preLoaderRoute: typeof DashboardBusinessAnalysisRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/blogs': {
      id: '/dashboard/blogs'
      path: '/blogs'
      fullPath: '/dashboard/blogs'
      preLoaderRoute: typeof DashboardBlogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/b2b-network': {
      id: '/dashboard/b2b-network'
      path: '/b2b-network'
      fullPath: '/dashboard/b2b-network'
      preLoaderRoute: typeof DashboardB2bNetworkRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/automation': {
      id: '/dashboard/automation'
      path: '/automation'
      fullPath: '/dashboard/automation'
      preLoaderRoute: typeof DashboardAutomationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/aeo-geo': {
      id: '/dashboard/aeo-geo'
      path: '/aeo-geo'
      fullPath: '/dashboard/aeo-geo'
      preLoaderRoute: typeof DashboardAeoGeoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/actions': {
      id: '/dashboard/actions'
      path: '/actions'
      fullPath: '/dashboard/actions'
      preLoaderRoute: typeof DashboardActionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agents/': {
      id: '/dashboard/agents/'
      path: '/agents'
      fullPath: '/dashboard/agents/'
      preLoaderRoute: typeof DashboardAgentsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/business-analysis/old': {
      id: '/dashboard/business-analysis/old'
      path: '/old'
      fullPath: '/dashboard/business-analysis/old'
      preLoaderRoute: typeof DashboardBusinessAnalysisOldRouteImport
      parentRoute: typeof DashboardBusinessAnalysisRoute
    }
    '/dashboard/agents/partnership': {
      id: '/dashboard/agents/partnership'
      path: '/agents/partnership'
      fullPath: '/dashboard/agents/partnership'
      preLoaderRoute: typeof DashboardAgentsPartnershipRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agents/customer-retention': {
      id: '/dashboard/agents/customer-retention'
      path: '/agents/customer-retention'
      fullPath: '/dashboard/agents/customer-retention'
      preLoaderRoute: typeof DashboardAgentsCustomerRetentionRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardBusinessAnalysisRouteChildren {
  DashboardBusinessAnalysisOldRoute: typeof DashboardBusinessAnalysisOldRoute
}

const DashboardBusinessAnalysisRouteChildren: DashboardBusinessAnalysisRouteChildren =
  {
    DashboardBusinessAnalysisOldRoute: DashboardBusinessAnalysisOldRoute,
  }

const DashboardBusinessAnalysisRouteWithChildren =
  DashboardBusinessAnalysisRoute._addFileChildren(
    DashboardBusinessAnalysisRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardActionsRoute: typeof DashboardActionsRoute
  DashboardAeoGeoRoute: typeof DashboardAeoGeoRoute
  DashboardAutomationRoute: typeof DashboardAutomationRoute
  DashboardB2bNetworkRoute: typeof DashboardB2bNetworkRoute
  DashboardBlogsRoute: typeof DashboardBlogsRoute
  DashboardBusinessAnalysisRoute: typeof DashboardBusinessAnalysisRouteWithChildren
  DashboardBusinessDetailsRoute: typeof DashboardBusinessDetailsRoute
  DashboardCompetitorAnalysisRoute: typeof DashboardCompetitorAnalysisRoute
  DashboardCompetitorsRoute: typeof DashboardCompetitorsRoute
  DashboardContentRoute: typeof DashboardContentRoute
  DashboardCustomersRoute: typeof DashboardCustomersRoute
  DashboardDailyAskRoute: typeof DashboardDailyAskRoute
  DashboardGrowthRoute: typeof DashboardGrowthRoute
  DashboardInsightsRoute: typeof DashboardInsightsRoute
  DashboardInstagramRoute: typeof DashboardInstagramRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardPricingRoute: typeof DashboardPricingRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardReviewReplyRoute: typeof DashboardReviewReplyRoute
  DashboardSeoRoute: typeof DashboardSeoRoute
  DashboardSeoGoogleMapsRoute: typeof DashboardSeoGoogleMapsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardWebsiteRoute: typeof DashboardWebsiteRoute
  DashboardWhatsappRoute: typeof DashboardWhatsappRoute
  DashboardWhatsappSalesRoute: typeof DashboardWhatsappSalesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAgentsCustomerRetentionRoute: typeof DashboardAgentsCustomerRetentionRoute
  DashboardAgentsPartnershipRoute: typeof DashboardAgentsPartnershipRoute
  DashboardAgentsIndexRoute: typeof DashboardAgentsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardActionsRoute: DashboardActionsRoute,
  DashboardAeoGeoRoute: DashboardAeoGeoRoute,
  DashboardAutomationRoute: DashboardAutomationRoute,
  DashboardB2bNetworkRoute: DashboardB2bNetworkRoute,
  DashboardBlogsRoute: DashboardBlogsRoute,
  DashboardBusinessAnalysisRoute: DashboardBusinessAnalysisRouteWithChildren,
  DashboardBusinessDetailsRoute: DashboardBusinessDetailsRoute,
  DashboardCompetitorAnalysisRoute: DashboardCompetitorAnalysisRoute,
  DashboardCompetitorsRoute: DashboardCompetitorsRoute,
  DashboardContentRoute: DashboardContentRoute,
  DashboardCustomersRoute: DashboardCustomersRoute,
  DashboardDailyAskRoute: DashboardDailyAskRoute,
  DashboardGrowthRoute: DashboardGrowthRoute,
  DashboardInsightsRoute: DashboardInsightsRoute,
  DashboardInstagramRoute: DashboardInstagramRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardPricingRoute: DashboardPricingRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardReviewReplyRoute: DashboardReviewReplyRoute,
  DashboardSeoRoute: DashboardSeoRoute,
  DashboardSeoGoogleMapsRoute: DashboardSeoGoogleMapsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardWebsiteRoute: DashboardWebsiteRoute,
  DashboardWhatsappRoute: DashboardWhatsappRoute,
  DashboardWhatsappSalesRoute: DashboardWhatsappSalesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAgentsCustomerRetentionRoute: DashboardAgentsCustomerRetentionRoute,
  DashboardAgentsPartnershipRoute: DashboardAgentsPartnershipRoute,
  DashboardAgentsIndexRoute: DashboardAgentsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  VerifyRoute: VerifyRoute,
  WebsiteWebsiteIdRoute: WebsiteWebsiteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
