/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as WebsiteWebsiteIdRouteImport } from './routes/website.$websiteId'
import { Route as DashboardWhatsappSalesRouteImport } from './routes/dashboard.whatsapp-sales'
import { Route as DashboardWebsiteRouteImport } from './routes/dashboard.website'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSeoRouteImport } from './routes/dashboard.seo'
import { Route as DashboardReviewReplyRouteImport } from './routes/dashboard.review-reply'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardPricingRouteImport } from './routes/dashboard.pricing'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard.messages'
import { Route as DashboardInstagramRouteImport } from './routes/dashboard.instagram'
import { Route as DashboardInsightsRouteImport } from './routes/dashboard.insights'
import { Route as DashboardGrowthRouteImport } from './routes/dashboard.growth'
import { Route as DashboardCustomersRouteImport } from './routes/dashboard.customers'
import { Route as DashboardContentRouteImport } from './routes/dashboard.content'
import { Route as DashboardCompetitorsRouteImport } from './routes/dashboard.competitors'
import { Route as DashboardBusinessDetailsRouteImport } from './routes/dashboard.business-details'
import { Route as DashboardBusinessAnalysisRouteImport } from './routes/dashboard.business-analysis'
import { Route as DashboardAutomationRouteImport } from './routes/dashboard.automation'
import { Route as DashboardActionsRouteImport } from './routes/dashboard.actions'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const WebsiteWebsiteIdRoute = WebsiteWebsiteIdRouteImport.update({
  id: '/website/$websiteId',
  path: '/website/$websiteId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWhatsappSalesRoute = DashboardWhatsappSalesRouteImport.update({
  id: '/whatsapp-sales',
  path: '/whatsapp-sales',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWebsiteRoute = DashboardWebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSeoRoute = DashboardSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReviewReplyRoute = DashboardReviewReplyRouteImport.update({
  id: '/review-reply',
  path: '/review-reply',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPricingRoute = DashboardPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInstagramRoute = DashboardInstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInsightsRoute = DashboardInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGrowthRoute = DashboardGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomersRoute = DashboardCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContentRoute = DashboardContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCompetitorsRoute = DashboardCompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBusinessDetailsRoute =
  DashboardBusinessDetailsRouteImport.update({
    id: '/business-details',
    path: '/business-details',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardBusinessAnalysisRoute =
  DashboardBusinessAnalysisRouteImport.update({
    id: '/business-analysis',
    path: '/business-analysis',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAutomationRoute = DashboardAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardActionsRoute = DashboardActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/dashboard/actions': typeof DashboardActionsRoute
  '/dashboard/automation': typeof DashboardAutomationRoute
  '/dashboard/business-analysis': typeof DashboardBusinessAnalysisRoute
  '/dashboard/business-details': typeof DashboardBusinessDetailsRoute
  '/dashboard/competitors': typeof DashboardCompetitorsRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/growth': typeof DashboardGrowthRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/instagram': typeof DashboardInstagramRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/pricing': typeof DashboardPricingRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/review-reply': typeof DashboardReviewReplyRoute
  '/dashboard/seo': typeof DashboardSeoRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/website': typeof DashboardWebsiteRoute
  '/dashboard/whatsapp-sales': typeof DashboardWhatsappSalesRoute
  '/website/$websiteId': typeof WebsiteWebsiteIdRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/dashboard/actions': typeof DashboardActionsRoute
  '/dashboard/automation': typeof DashboardAutomationRoute
  '/dashboard/business-analysis': typeof DashboardBusinessAnalysisRoute
  '/dashboard/business-details': typeof DashboardBusinessDetailsRoute
  '/dashboard/competitors': typeof DashboardCompetitorsRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/growth': typeof DashboardGrowthRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/instagram': typeof DashboardInstagramRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/pricing': typeof DashboardPricingRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/review-reply': typeof DashboardReviewReplyRoute
  '/dashboard/seo': typeof DashboardSeoRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/website': typeof DashboardWebsiteRoute
  '/dashboard/whatsapp-sales': typeof DashboardWhatsappSalesRoute
  '/website/$websiteId': typeof WebsiteWebsiteIdRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/dashboard/actions': typeof DashboardActionsRoute
  '/dashboard/automation': typeof DashboardAutomationRoute
  '/dashboard/business-analysis': typeof DashboardBusinessAnalysisRoute
  '/dashboard/business-details': typeof DashboardBusinessDetailsRoute
  '/dashboard/competitors': typeof DashboardCompetitorsRoute
  '/dashboard/content': typeof DashboardContentRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/growth': typeof DashboardGrowthRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/instagram': typeof DashboardInstagramRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/pricing': typeof DashboardPricingRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/review-reply': typeof DashboardReviewReplyRoute
  '/dashboard/seo': typeof DashboardSeoRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/website': typeof DashboardWebsiteRoute
  '/dashboard/whatsapp-sales': typeof DashboardWhatsappSalesRoute
  '/website/$websiteId': typeof WebsiteWebsiteIdRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/verify'
    | '/dashboard/actions'
    | '/dashboard/automation'
    | '/dashboard/business-analysis'
    | '/dashboard/business-details'
    | '/dashboard/competitors'
    | '/dashboard/content'
    | '/dashboard/customers'
    | '/dashboard/growth'
    | '/dashboard/insights'
    | '/dashboard/instagram'
    | '/dashboard/messages'
    | '/dashboard/pricing'
    | '/dashboard/reports'
    | '/dashboard/review-reply'
    | '/dashboard/seo'
    | '/dashboard/settings'
    | '/dashboard/website'
    | '/dashboard/whatsapp-sales'
    | '/website/$websiteId'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/verify'
    | '/dashboard/actions'
    | '/dashboard/automation'
    | '/dashboard/business-analysis'
    | '/dashboard/business-details'
    | '/dashboard/competitors'
    | '/dashboard/content'
    | '/dashboard/customers'
    | '/dashboard/growth'
    | '/dashboard/insights'
    | '/dashboard/instagram'
    | '/dashboard/messages'
    | '/dashboard/pricing'
    | '/dashboard/reports'
    | '/dashboard/review-reply'
    | '/dashboard/seo'
    | '/dashboard/settings'
    | '/dashboard/website'
    | '/dashboard/whatsapp-sales'
    | '/website/$websiteId'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/verify'
    | '/dashboard/actions'
    | '/dashboard/automation'
    | '/dashboard/business-analysis'
    | '/dashboard/business-details'
    | '/dashboard/competitors'
    | '/dashboard/content'
    | '/dashboard/customers'
    | '/dashboard/growth'
    | '/dashboard/insights'
    | '/dashboard/instagram'
    | '/dashboard/messages'
    | '/dashboard/pricing'
    | '/dashboard/reports'
    | '/dashboard/review-reply'
    | '/dashboard/seo'
    | '/dashboard/settings'
    | '/dashboard/website'
    | '/dashboard/whatsapp-sales'
    | '/website/$websiteId'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  VerifyRoute: typeof VerifyRoute
  WebsiteWebsiteIdRoute: typeof WebsiteWebsiteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/website/$websiteId': {
      id: '/website/$websiteId'
      path: '/website/$websiteId'
      fullPath: '/website/$websiteId'
      preLoaderRoute: typeof WebsiteWebsiteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/whatsapp-sales': {
      id: '/dashboard/whatsapp-sales'
      path: '/whatsapp-sales'
      fullPath: '/dashboard/whatsapp-sales'
      preLoaderRoute: typeof DashboardWhatsappSalesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/website': {
      id: '/dashboard/website'
      path: '/website'
      fullPath: '/dashboard/website'
      preLoaderRoute: typeof DashboardWebsiteRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/seo': {
      id: '/dashboard/seo'
      path: '/seo'
      fullPath: '/dashboard/seo'
      preLoaderRoute: typeof DashboardSeoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/review-reply': {
      id: '/dashboard/review-reply'
      path: '/review-reply'
      fullPath: '/dashboard/review-reply'
      preLoaderRoute: typeof DashboardReviewReplyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pricing': {
      id: '/dashboard/pricing'
      path: '/pricing'
      fullPath: '/dashboard/pricing'
      preLoaderRoute: typeof DashboardPricingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/instagram': {
      id: '/dashboard/instagram'
      path: '/instagram'
      fullPath: '/dashboard/instagram'
      preLoaderRoute: typeof DashboardInstagramRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/insights': {
      id: '/dashboard/insights'
      path: '/insights'
      fullPath: '/dashboard/insights'
      preLoaderRoute: typeof DashboardInsightsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/growth': {
      id: '/dashboard/growth'
      path: '/growth'
      fullPath: '/dashboard/growth'
      preLoaderRoute: typeof DashboardGrowthRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/customers': {
      id: '/dashboard/customers'
      path: '/customers'
      fullPath: '/dashboard/customers'
      preLoaderRoute: typeof DashboardCustomersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/content': {
      id: '/dashboard/content'
      path: '/content'
      fullPath: '/dashboard/content'
      preLoaderRoute: typeof DashboardContentRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/competitors': {
      id: '/dashboard/competitors'
      path: '/competitors'
      fullPath: '/dashboard/competitors'
      preLoaderRoute: typeof DashboardCompetitorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/business-details': {
      id: '/dashboard/business-details'
      path: '/business-details'
      fullPath: '/dashboard/business-details'
      preLoaderRoute: typeof DashboardBusinessDetailsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/business-analysis': {
      id: '/dashboard/business-analysis'
      path: '/business-analysis'
      fullPath: '/dashboard/business-analysis'
      preLoaderRoute: typeof DashboardBusinessAnalysisRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/automation': {
      id: '/dashboard/automation'
      path: '/automation'
      fullPath: '/dashboard/automation'
      preLoaderRoute: typeof DashboardAutomationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/actions': {
      id: '/dashboard/actions'
      path: '/actions'
      fullPath: '/dashboard/actions'
      preLoaderRoute: typeof DashboardActionsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardActionsRoute: typeof DashboardActionsRoute
  DashboardAutomationRoute: typeof DashboardAutomationRoute
  DashboardBusinessAnalysisRoute: typeof DashboardBusinessAnalysisRoute
  DashboardBusinessDetailsRoute: typeof DashboardBusinessDetailsRoute
  DashboardCompetitorsRoute: typeof DashboardCompetitorsRoute
  DashboardContentRoute: typeof DashboardContentRoute
  DashboardCustomersRoute: typeof DashboardCustomersRoute
  DashboardGrowthRoute: typeof DashboardGrowthRoute
  DashboardInsightsRoute: typeof DashboardInsightsRoute
  DashboardInstagramRoute: typeof DashboardInstagramRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardPricingRoute: typeof DashboardPricingRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardReviewReplyRoute: typeof DashboardReviewReplyRoute
  DashboardSeoRoute: typeof DashboardSeoRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardWebsiteRoute: typeof DashboardWebsiteRoute
  DashboardWhatsappSalesRoute: typeof DashboardWhatsappSalesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardActionsRoute: DashboardActionsRoute,
  DashboardAutomationRoute: DashboardAutomationRoute,
  DashboardBusinessAnalysisRoute: DashboardBusinessAnalysisRoute,
  DashboardBusinessDetailsRoute: DashboardBusinessDetailsRoute,
  DashboardCompetitorsRoute: DashboardCompetitorsRoute,
  DashboardContentRoute: DashboardContentRoute,
  DashboardCustomersRoute: DashboardCustomersRoute,
  DashboardGrowthRoute: DashboardGrowthRoute,
  DashboardInsightsRoute: DashboardInsightsRoute,
  DashboardInstagramRoute: DashboardInstagramRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardPricingRoute: DashboardPricingRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardReviewReplyRoute: DashboardReviewReplyRoute,
  DashboardSeoRoute: DashboardSeoRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardWebsiteRoute: DashboardWebsiteRoute,
  DashboardWhatsappSalesRoute: DashboardWhatsappSalesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  VerifyRoute: VerifyRoute,
  WebsiteWebsiteIdRoute: WebsiteWebsiteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
